# Generated by Django 4.2.16 on 2025-02-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartrate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("PATIENT", "Patient"),
                    ("DOCTOR", "Doctor"),
                    ("NURSE", "Nurse"),
                    ("ADMIN", "Administrator"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
